<template>
    <InteriorBanner></InteriorBanner>
    <InteriorGalery></InteriorGalery>
    <InteriorWhychoose></InteriorWhychoose>
    <InteriorSlide></InteriorSlide>
    <InteriorTimeline></InteriorTimeline>
    <InteriorInterest></InteriorInterest>
    <InteriorNeed></InteriorNeed>
    <InteriorContact></InteriorContact>
    <InteriorOtherService></InteriorOtherService>
</template>